# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yaml_form_helper}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Michael Gerber}]
  s.date = %q{2011-08-09}
  s.description = %q{The YamlFormHelper is a Rails Plugin that extends the FormBuilder Class with methods to create form tags for the HTML/CSS Framework YAML (http://www.yaml.de/)}
  s.email = [%q{mike@citrin.ch}]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README",
    "Rakefile",
    "app/helpers/yaml_form_helper.rb",
    "install.rb",
    "lib/yaml_form_helper.rb",
    "lib/yaml_form_helper/form_builder_ext.rb",
    "rails/init.rb",
    "test/test_helper.rb",
    "test/yaml_form_helper_test.rb",
    "uninstall.rb",
    "yaml_form_helper.gemspec"
  ]
  s.homepage = %q{https://github.com/servasat/yaml_form_helper}
  s.require_paths = [%q{lib}]
  s.rubyforge_project = %q{yaml_form_helper}
  s.rubygems_version = %q{1.8.7}
  s.summary = %q{Rails Plugin for YAML Forms}
  s.test_files = [%q{test/test_helper.rb}, %q{test/yaml_form_helper_test.rb}]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

